filemanager_index:
    path:       /
    defaults:   {_controller: "FilemanagerBundle:Filemanager:index"}
filemanager_actions:
    path:       /do
    defaults:   {_controller: "FilemanagerBundle:Filemanager:do"}

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"