<?php

namespace Core\FilemanagerBundle\Repository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
/**
 * FoldersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoldersRepository extends NestedTreeRepository
{
}
